const field3 = [
    { name: "tuz", img: "tuz.png" },
    { name: "karol" , img: "karol.png" },
    { name: "dam", img: "dam.png" },
    { name: "valet", img: "valet.png" },
    { name: "ten", img: "ten.png" },
    { name: "nine", img: "nine.png" },
    { name: "eight", img: "eight.png" },
    { name: "seven", img: "seven.png" },
    { name: "six", img: "six.png" },
    { name: "five", img: "five.png"},
    { name: "for", img: "for.png" },
    { name: "three", img: "three.png" },
    { name: "two", img: "two.png" },
    { name: "one", img: "one.png"},
    { name: "joker", img: "joker.png" },
    { name: "image1", img: "image1.png"},
    { name: "image2", img: "image2.png"},
    { name: "image3", img: "image3.png"},
    { name: "image4", img: "image4.png"},
    { name: "image5", img: "image5.png"},
    { name: "image6", img: "image6.png"},
    { name: "image7", img: "image7.png"},
    { name: "image8", img: "image8.png"},
    { name: "image9", img: "image9.png"},
    { name: "image10", img: "image10.png"},
    { name: "image11", img: "image11.png"},
    { name: "image12", img: "image12.png"},
    { name: "image13", img: "image13.png"},
    { name: "image14", img: "image14.png"},
    { name: "image15", img: "image15.png"},
    { name: "image16", img: "image16.png"},
    { name: "image17", img: "image17.png"},
]
